name: Android Build & Release

on:
  push:
    tags:
      - 'v*' # Se activa con tags tipo v1.16.0

jobs:
  build:
    runs-on: ubuntu-latest
    # Permisos para que el robot pueda subir archivos a la sección de Releases
    permissions:
      contents: write
      
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Hacer el APK ejecutable
        run: chmod +x gradlew

      # --- NUEVO PASO: Inyectar la API Key en el servidor ---
      # Esto crea el archivo secreto al vuelo usando el Secret de GitHub
      - name: Crear local.properties con API Key
        run: echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > local.properties

      - name: Compilar APK de Release
        run: ./gradlew assembleRelease

      - name: Instalar Android Build Tools 29.0.3
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;29.0.3"

      - name: Firmar el APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      # --- PASO CLAVE: Renombrar el archivo firmado a un nombre fijo ---
      - name: Renombrar APK para la Release
        run: mv ${{ steps.sign_app.outputs.signedReleaseFile }} app/build/outputs/apk/release/Riffle.apk

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v1
        with:
          # Subimos el archivo con el nombre nuevo y limpio
          files: app/build/outputs/apk/release/Riffle.apk
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}